feat: Constraints API v0
gattaca-com/helix pull request #49
Opened 2024-11-07 10:49 UTC by thedevbirb

This PR introduces the [Constraints API](https://docs.boltprotocol.xyz/technical-docs/api/builder) in Helix.

2024-11-07 10:52 UTC, merklefruit commented on crates/api/src/constraints/api.rs
> +    /// Implements this API: <https://docs.boltprotocol.xyz/api/builder#constraints>
broken link, update to https://docs.boltprotocol.xyz/technical-docs/api/builder#constraints

2024-11-07 10:58 UTC, merklefruit requested changes
Just tagging some broken docs links

2024-11-07 10:58 UTC, merklefruit commented on crates/api/src/constraints/api.rs
> +    /// Implements this API: <https://docs.boltprotocol.xyz/api/builder#constraints>
update to https://docs.boltprotocol.xyz/technical-docs/api/builder#constraints

2024-11-07 10:58 UTC, merklefruit commented on crates/api/src/constraints/api.rs
> +    /// Implements this API: <https://docs.boltprotocol.xyz/api/builder#delegate>
update to https://docs.boltprotocol.xyz/technical-docs/api/builder#delegate

2024-11-07 10:58 UTC, merklefruit commented on crates/api/src/constraints/api.rs
> +    /// Implements this API: <https://docs.boltprotocol.xyz/api/builder#revoke>
update to https://docs.boltprotocol.xyz/technical-docs/api/builder#revoke

2024-11-07 10:58 UTC, merklefruit commented on crates/api/src/proposer/api.rs
> +    /// Implements this API: <https://docs.boltprotocol.xyz/api/builder#get_header_with_proofs>
update to https://docs.boltprotocol.xyz/technical-docs/api/builder#get_header_with_proofs

2024-11-07 10:58 UTC, merklefruit commented on crates/common/src/config.rs
> +    SubmitBlockWithProofs,
all these links need to be updated

2024-11-07 10:58 UTC, merklefruit commented on crates/common/src/bid_submission/submission.rs
> +    /// Reference: <https://docs.boltprotocol.xyz/api/builder#get_header_with_proofs>
update to https://docs.boltprotocol.xyz/technical-docs/api/builder#get_header_with_proofs

2024-11-25 18:28 UTC, gd-0 commented on crates/common/src/api/constraints_api.rs
> +        hasher.update(&self.delegatee_pubkey.to_vec());
`as_slice` can be used here to save the intermediate allocation.  (same with the `to_vec` lower in this file)
```suggestion
        hasher.update(self.validator_pubkey.as_slice());
        hasher.update(self.delegatee_pubkey.as_slice());
```

2024-11-25 18:40 UTC, gd-0 commented on crates/common/src/proofs.rs
> +                .map_err(|e| ProofError::DecodingFailed(e.to_string()))?;
Can save an allocation here
```suggestion
        for transaction in value.message.transactions.iter() {
            let tx = PooledTransactionsElement::decode_enveloped(Bytes::copy_from_slice(transaction.as_slice()))
                .map_err(|e| ProofError::DecodingFailed(e.to_string()))?;
```

2024-11-25 18:55 UTC, gd-0 commented on crates/api/src/constraints/api.rs
> +        });
we really shouldn't call the db here if possible. We run a single db instance in prod so we could be fetching from Tokyo -> FR every time this is called.

Ideally we should store proposer duties in redis in the housekeeper. then do `api.auctioneer.get_proposer_duties` instead

2024-11-25 19:00 UTC, gd-0 commented on crates/api/src/builder/api.rs
> +    pub async fn submit_block_with_proofs(
As far as I can see this function is identical to `submit_block` except it might verify the proofs? can these two functions call a common fn that has a flag to verify proofs or not?

2024-11-25 19:50 UTC, 0w3n-d approved these changes
My main issue with this PR is it seems to assume everything is talking to the same redis. But maybe we can fix this in a follow up PR.

2024-11-25 19:50 UTC, 0w3n-d commented on crates/api/src/constraints/api.rs
> +        });
Yeah in the other apis we store these in memory and keep them updated with the chain updater. Should just do the same here?

2024-11-26 10:39 UTC, thedevbirb commented on crates/api/src/builder/api.rs
> +    pub async fn submit_block_with_proofs(
You're right! Actually I was planning to keep the same underlying implementation for both endpoints, for the reasons mentioned in https://github.com/chainbound/helix/pull/28. What do you think?

2024-11-27 08:37 UTC, gd-0 commented on crates/api/src/builder/api.rs
> +    pub async fn submit_block_with_proofs(
Yep sounds good to me!

2024-11-29 14:25 UTC, merged